services:
  - docker

before_install:
  - docker-compose up -d 
  - sleep 20
  - make librdkafka
  - cd fRanz

language: r
r: 
  - release
cache: packages
addons:
  apt:
    packages:
    - librdkafka-dev
